/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OfferingType = IDL.Variant({
  'art' : IDL.Null,
  'wisdom' : IDL.Null,
  'breathwork' : IDL.Null,
  'oneOnOne' : IDL.Null,
});
export const GroupInfo = IDL.Record({
  'id' : IDL.Text,
  'members' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'voidId' : IDL.Text,
  'e2eePublicKey' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'cosmicHandle' : IDL.Opt(IDL.Text),
});
export const NFTCategory = IDL.Variant({
  'guidedBreathwork' : IDL.Null,
  'sageReflection' : IDL.Null,
  'deepShadow' : IDL.Null,
  'lightWisdom' : IDL.Null,
});
export const CosmicNFT = IDL.Record({
  'id' : IDL.Nat,
  'postText' : IDL.Text,
  'creator' : IDL.Principal,
  'resonanceCount' : IDL.Nat,
  'lineage' : IDL.Vec(IDL.Text),
  'rareTrait' : IDL.Opt(IDL.Text),
  'metadataJson' : IDL.Text,
  'creatorVoidId' : IDL.Text,
  'mintedAt' : IDL.Int,
  'wisdomScore' : IDL.Nat,
  'category' : NFTCategory,
  'priceVoid' : IDL.Nat,
  'isForSale' : IDL.Bool,
});
export const MessageType = IDL.Variant({
  'file' : IDL.Null,
  'text' : IDL.Null,
  'image' : IDL.Null,
});
export const Message = IDL.Record({
  'id' : IDL.Text,
  'upvotes' : IDL.Nat,
  'senderVoidId' : IDL.Text,
  'ciphertext' : IDL.Text,
  'keywords' : IDL.Vec(IDL.Text),
  'messageType' : MessageType,
  'timestamp' : IDL.Int,
  'blobId' : IDL.Opt(IDL.Text),
  'replyTo' : IDL.Opt(IDL.Text),
});
export const ValueOffering = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'creatorVoidId' : IDL.Text,
  'isActive' : IDL.Bool,
  'offeringType' : OfferingType,
  'priceVoid' : IDL.Nat,
});
export const ChannelType = IDL.Variant({
  'dm' : IDL.Text,
  'darkRoom' : IDL.Null,
  'group' : IDL.Text,
  'lightRoom' : IDL.Null,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGroupMember' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'buyNFT' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'createDM' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'createGroup' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'createValueOffering' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, OfferingType, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deactivateOffering' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'generateInviteToken' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllGroups' : IDL.Func([], [IDL.Vec(GroupInfo)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCosmicHandle' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getDailyReflection' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getE2EEPublicKey' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  'getGroupInfo' : IDL.Func([IDL.Text], [IDL.Opt(GroupInfo)], ['query']),
  'getGroupsForVoidId' : IDL.Func([IDL.Text], [IDL.Vec(GroupInfo)], ['query']),
  'getMarketplaceListings' : IDL.Func(
      [IDL.Opt(NFTCategory)],
      [IDL.Vec(CosmicNFT)],
      ['query'],
    ),
  'getMessages' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Vec(Message)], ['query']),
  'getMessagesByKeyword' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getMintablePost' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'getNFT' : IDL.Func([IDL.Nat], [IDL.Opt(CosmicNFT)], ['query']),
  'getNFTsByCreator' : IDL.Func([IDL.Text], [IDL.Vec(CosmicNFT)], ['query']),
  'getOfferingsByCreator' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ValueOffering)],
      ['query'],
    ),
  'getPinnedMessage' : IDL.Func([IDL.Text], [IDL.Opt(Message)], ['query']),
  'getRoyaltiesEarned' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getUserNFTs' : IDL.Func([IDL.Text], [IDL.Vec(CosmicNFT)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getValueOfferings' : IDL.Func([], [IDL.Vec(ValueOffering)], ['query']),
  'getWisdomScore' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listChannels' : IDL.Func([], [IDL.Vec(ChannelType)], ['query']),
  'listNFTForSale' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'loadOlderMessages' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Nat],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'mintNFT' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, NFTCategory, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'pinMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'postMessage' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        MessageType,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'postMessageWithKeywords' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        MessageType,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'removeGroupMember' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'resolveInviteToken' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'resonateNFT' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setCosmicHandle' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setDailyReflection' : IDL.Func([IDL.Text], [], []),
  'storeE2EEPublicKey' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
  'upvoteMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OfferingType = IDL.Variant({
    'art' : IDL.Null,
    'wisdom' : IDL.Null,
    'breathwork' : IDL.Null,
    'oneOnOne' : IDL.Null,
  });
  const GroupInfo = IDL.Record({
    'id' : IDL.Text,
    'members' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'voidId' : IDL.Text,
    'e2eePublicKey' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'cosmicHandle' : IDL.Opt(IDL.Text),
  });
  const NFTCategory = IDL.Variant({
    'guidedBreathwork' : IDL.Null,
    'sageReflection' : IDL.Null,
    'deepShadow' : IDL.Null,
    'lightWisdom' : IDL.Null,
  });
  const CosmicNFT = IDL.Record({
    'id' : IDL.Nat,
    'postText' : IDL.Text,
    'creator' : IDL.Principal,
    'resonanceCount' : IDL.Nat,
    'lineage' : IDL.Vec(IDL.Text),
    'rareTrait' : IDL.Opt(IDL.Text),
    'metadataJson' : IDL.Text,
    'creatorVoidId' : IDL.Text,
    'mintedAt' : IDL.Int,
    'wisdomScore' : IDL.Nat,
    'category' : NFTCategory,
    'priceVoid' : IDL.Nat,
    'isForSale' : IDL.Bool,
  });
  const MessageType = IDL.Variant({
    'file' : IDL.Null,
    'text' : IDL.Null,
    'image' : IDL.Null,
  });
  const Message = IDL.Record({
    'id' : IDL.Text,
    'upvotes' : IDL.Nat,
    'senderVoidId' : IDL.Text,
    'ciphertext' : IDL.Text,
    'keywords' : IDL.Vec(IDL.Text),
    'messageType' : MessageType,
    'timestamp' : IDL.Int,
    'blobId' : IDL.Opt(IDL.Text),
    'replyTo' : IDL.Opt(IDL.Text),
  });
  const ValueOffering = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'creatorVoidId' : IDL.Text,
    'isActive' : IDL.Bool,
    'offeringType' : OfferingType,
    'priceVoid' : IDL.Nat,
  });
  const ChannelType = IDL.Variant({
    'dm' : IDL.Text,
    'darkRoom' : IDL.Null,
    'group' : IDL.Text,
    'lightRoom' : IDL.Null,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGroupMember' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'buyNFT' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'createDM' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'createGroup' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'createValueOffering' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, OfferingType, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deactivateOffering' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'generateInviteToken' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllGroups' : IDL.Func([], [IDL.Vec(GroupInfo)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCosmicHandle' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getDailyReflection' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getE2EEPublicKey' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    'getGroupInfo' : IDL.Func([IDL.Text], [IDL.Opt(GroupInfo)], ['query']),
    'getGroupsForVoidId' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(GroupInfo)],
        ['query'],
      ),
    'getMarketplaceListings' : IDL.Func(
        [IDL.Opt(NFTCategory)],
        [IDL.Vec(CosmicNFT)],
        ['query'],
      ),
    'getMessages' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getMessagesByKeyword' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getMintablePost' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'getNFT' : IDL.Func([IDL.Nat], [IDL.Opt(CosmicNFT)], ['query']),
    'getNFTsByCreator' : IDL.Func([IDL.Text], [IDL.Vec(CosmicNFT)], ['query']),
    'getOfferingsByCreator' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ValueOffering)],
        ['query'],
      ),
    'getPinnedMessage' : IDL.Func([IDL.Text], [IDL.Opt(Message)], ['query']),
    'getRoyaltiesEarned' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getUserNFTs' : IDL.Func([IDL.Text], [IDL.Vec(CosmicNFT)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getValueOfferings' : IDL.Func([], [IDL.Vec(ValueOffering)], ['query']),
    'getWisdomScore' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listChannels' : IDL.Func([], [IDL.Vec(ChannelType)], ['query']),
    'listNFTForSale' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'loadOlderMessages' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Nat],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'mintNFT' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, NFTCategory, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'pinMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'postMessage' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          MessageType,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'postMessageWithKeywords' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          MessageType,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'removeGroupMember' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'resolveInviteToken' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'resonateNFT' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setCosmicHandle' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setDailyReflection' : IDL.Func([IDL.Text], [], []),
    'storeE2EEPublicKey' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
    'upvoteMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };