/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'voidId' : IDL.Text,
  'cosmicHandle' : IDL.Opt(IDL.Text),
});
export const MessageType = IDL.Variant({
  'file' : IDL.Null,
  'text' : IDL.Null,
  'image' : IDL.Null,
});
export const Message = IDL.Record({
  'id' : IDL.Text,
  'upvotes' : IDL.Nat,
  'senderVoidId' : IDL.Text,
  'ciphertext' : IDL.Text,
  'keywords' : IDL.Vec(IDL.Text),
  'messageType' : MessageType,
  'timestamp' : IDL.Int,
  'blobId' : IDL.Opt(IDL.Text),
  'replyTo' : IDL.Opt(IDL.Text),
});
export const ChannelType = IDL.Variant({
  'dm' : IDL.Text,
  'darkRoom' : IDL.Null,
  'lightRoom' : IDL.Null,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'associateBlobWithMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'createDM' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'generateInviteToken' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCosmicHandle' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getDailyReflection' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getMessages' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Vec(Message)], ['query']),
  'getMessagesByKeyword' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getPinnedMessage' : IDL.Func([IDL.Text], [IDL.Opt(Message)], ['query']),
  'getSortedDMs' : IDL.Func([], [IDL.Vec(ChannelType)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWisdomScore' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listChannels' : IDL.Func([], [IDL.Vec(ChannelType)], ['query']),
  'loadOlderMessages' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Nat],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'pinMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'postMessage' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        MessageType,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'postMessageWithKeywords' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        MessageType,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'resolveInviteToken' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setCosmicHandle' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setDailyReflection' : IDL.Func([IDL.Text], [], []),
  'upvoteMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'voidId' : IDL.Text,
    'cosmicHandle' : IDL.Opt(IDL.Text),
  });
  const MessageType = IDL.Variant({
    'file' : IDL.Null,
    'text' : IDL.Null,
    'image' : IDL.Null,
  });
  const Message = IDL.Record({
    'id' : IDL.Text,
    'upvotes' : IDL.Nat,
    'senderVoidId' : IDL.Text,
    'ciphertext' : IDL.Text,
    'keywords' : IDL.Vec(IDL.Text),
    'messageType' : MessageType,
    'timestamp' : IDL.Int,
    'blobId' : IDL.Opt(IDL.Text),
    'replyTo' : IDL.Opt(IDL.Text),
  });
  const ChannelType = IDL.Variant({
    'dm' : IDL.Text,
    'darkRoom' : IDL.Null,
    'lightRoom' : IDL.Null,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'associateBlobWithMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'createDM' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'generateInviteToken' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCosmicHandle' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getDailyReflection' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getMessages' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getMessagesByKeyword' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getPinnedMessage' : IDL.Func([IDL.Text], [IDL.Opt(Message)], ['query']),
    'getSortedDMs' : IDL.Func([], [IDL.Vec(ChannelType)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWisdomScore' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listChannels' : IDL.Func([], [IDL.Vec(ChannelType)], ['query']),
    'loadOlderMessages' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Nat],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'pinMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'postMessage' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          MessageType,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'postMessageWithKeywords' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          MessageType,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'resolveInviteToken' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setCosmicHandle' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setDailyReflection' : IDL.Func([IDL.Text], [], []),
    'upvoteMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };