/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ChannelType = { 'dm' : string } |
  { 'darkRoom' : null } |
  { 'group' : string } |
  { 'lightRoom' : null };
export interface CosmicNFT {
  'id' : bigint,
  'postText' : string,
  'creator' : Principal,
  'resonanceCount' : bigint,
  'lineage' : Array<string>,
  'rareTrait' : [] | [string],
  'metadataJson' : string,
  'creatorVoidId' : string,
  'mintedAt' : bigint,
  'wisdomScore' : bigint,
  'category' : NFTCategory,
  'priceVoid' : bigint,
  'isForSale' : boolean,
}
export interface GroupInfo {
  'id' : string,
  'members' : Array<string>,
  'name' : string,
  'createdAt' : bigint,
  'createdBy' : string,
}
export interface Message {
  'id' : string,
  'upvotes' : bigint,
  'senderVoidId' : string,
  'ciphertext' : string,
  'keywords' : Array<string>,
  'messageType' : MessageType,
  'timestamp' : bigint,
  'blobId' : [] | [string],
  'replyTo' : [] | [string],
}
export type MessageType = { 'file' : null } |
  { 'text' : null } |
  { 'image' : null };
export type NFTCategory = { 'guidedBreathwork' : null } |
  { 'sageReflection' : null } |
  { 'deepShadow' : null } |
  { 'lightWisdom' : null };
export type OfferingType = { 'art' : null } |
  { 'wisdom' : null } |
  { 'breathwork' : null } |
  { 'oneOnOne' : null };
export interface UserProfile {
  'voidId' : string,
  'cosmicHandle' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface ValueOffering {
  'id' : string,
  'title' : string,
  'createdAt' : bigint,
  'description' : string,
  'creatorVoidId' : string,
  'isActive' : boolean,
  'offeringType' : OfferingType,
  'priceVoid' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGroupMember' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'associateBlobWithMessage' : ActorMethod<[string, string, string], undefined>,
  'buyNFT' : ActorMethod<[bigint, string], undefined>,
  'createDM' : ActorMethod<[string, string], string>,
  'createGroup' : ActorMethod<[string, string], string>,
  'createValueOffering' : ActorMethod<
    [string, string, bigint, OfferingType, string],
    string
  >,
  'deactivateOffering' : ActorMethod<[string, string], undefined>,
  'generateInviteToken' : ActorMethod<[string], string>,
  'getAllGroups' : ActorMethod<[], Array<GroupInfo>>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCosmicHandle' : ActorMethod<[string], [] | [string]>,
  'getDailyReflection' : ActorMethod<[], [] | [string]>,
  'getGroupInfo' : ActorMethod<[string], [] | [GroupInfo]>,
  'getGroupsForVoidId' : ActorMethod<[string], Array<GroupInfo>>,
  'getMarketplaceListings' : ActorMethod<
    [[] | [NFTCategory]],
    Array<CosmicNFT>
  >,
  'getMessages' : ActorMethod<[string, bigint], Array<Message>>,
  'getMessagesByKeyword' : ActorMethod<
    [string, string, bigint],
    Array<Message>
  >,
  'getMintablePost' : ActorMethod<[bigint], boolean>,
  'getNFT' : ActorMethod<[bigint], [] | [CosmicNFT]>,
  'getNFTsByCreator' : ActorMethod<[string], Array<CosmicNFT>>,
  'getOfferingsByCreator' : ActorMethod<[string], Array<ValueOffering>>,
  'getPinnedMessage' : ActorMethod<[string], [] | [Message]>,
  'getRoyaltiesEarned' : ActorMethod<[string], bigint>,
  'getSortedDMs' : ActorMethod<[], Array<ChannelType>>,
  'getUserNFTs' : ActorMethod<[string], Array<CosmicNFT>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getValueOfferings' : ActorMethod<[], Array<ValueOffering>>,
  'getWisdomScore' : ActorMethod<[string], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listChannels' : ActorMethod<[], Array<ChannelType>>,
  'listNFTForSale' : ActorMethod<[bigint, bigint], undefined>,
  'loadOlderMessages' : ActorMethod<[string, bigint, bigint], Array<Message>>,
  'mintNFT' : ActorMethod<
    [string, bigint, string, NFTCategory, string, [] | [string]],
    bigint
  >,
  'pinMessage' : ActorMethod<[string, string], undefined>,
  'postMessage' : ActorMethod<
    [string, string, string, MessageType, [] | [string], [] | [string]],
    undefined
  >,
  'postMessageWithKeywords' : ActorMethod<
    [
      string,
      string,
      string,
      MessageType,
      [] | [string],
      [] | [string],
      Array<string>,
    ],
    undefined
  >,
  'removeGroupMember' : ActorMethod<[string, string], undefined>,
  'resolveInviteToken' : ActorMethod<[string], [] | [string]>,
  'resonateNFT' : ActorMethod<[bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setCosmicHandle' : ActorMethod<[string, string], undefined>,
  'setDailyReflection' : ActorMethod<[string], undefined>,
  'upvoteMessage' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];