/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ChannelType = { 'dm' : string } |
  { 'darkRoom' : null } |
  { 'lightRoom' : null };
export interface Message {
  'id' : string,
  'upvotes' : bigint,
  'senderVoidId' : string,
  'ciphertext' : string,
  'keywords' : Array<string>,
  'messageType' : MessageType,
  'timestamp' : bigint,
  'blobId' : [] | [string],
  'replyTo' : [] | [string],
}
export type MessageType = { 'file' : null } |
  { 'text' : null } |
  { 'image' : null };
export interface UserProfile {
  'voidId' : string,
  'cosmicHandle' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'associateBlobWithMessage' : ActorMethod<[string, string, string], undefined>,
  'createDM' : ActorMethod<[string, string], string>,
  'generateInviteToken' : ActorMethod<[string], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCosmicHandle' : ActorMethod<[string], [] | [string]>,
  'getMessages' : ActorMethod<[string, bigint], Array<Message>>,
  'getMessagesByKeyword' : ActorMethod<
    [string, string, bigint],
    Array<Message>
  >,
  'getSortedDMs' : ActorMethod<[], Array<ChannelType>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWisdomScore' : ActorMethod<[string], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listChannels' : ActorMethod<[], Array<ChannelType>>,
  'loadOlderMessages' : ActorMethod<[string, bigint, bigint], Array<Message>>,
  'postMessage' : ActorMethod<
    [string, string, string, MessageType, [] | [string], [] | [string]],
    undefined
  >,
  'postMessageWithKeywords' : ActorMethod<
    [
      string,
      string,
      string,
      MessageType,
      [] | [string],
      [] | [string],
      Array<string>,
    ],
    undefined
  >,
  'resolveInviteToken' : ActorMethod<[string], [] | [string]>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setCosmicHandle' : ActorMethod<[string, string], undefined>,
  'upvoteMessage' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];