/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CosmicNFT {
    id: bigint;
    postText: string;
    creator: Principal;
    resonanceCount: bigint;
    lineage: Array<string>;
    rareTrait?: string;
    metadataJson: string;
    creatorVoidId: string;
    mintedAt: bigint;
    wisdomScore: bigint;
    category: NFTCategory;
    priceVoid: bigint;
    isForSale: boolean;
}
export interface GroupInfo {
    id: string;
    members: Array<string>;
    name: string;
    createdAt: bigint;
    createdBy: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type ChannelType = {
    __kind__: "dm";
    dm: string;
} | {
    __kind__: "darkRoom";
    darkRoom: null;
} | {
    __kind__: "group";
    group: string;
} | {
    __kind__: "lightRoom";
    lightRoom: null;
};
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Message {
    id: string;
    upvotes: bigint;
    senderVoidId: string;
    ciphertext: string;
    keywords: Array<string>;
    messageType: MessageType;
    timestamp: bigint;
    blobId?: string;
    replyTo?: string;
}
export interface ValueOffering {
    id: string;
    title: string;
    createdAt: bigint;
    description: string;
    creatorVoidId: string;
    isActive: boolean;
    offeringType: OfferingType;
    priceVoid: bigint;
}
export interface UserProfile {
    voidId: string;
    e2eePublicKey?: Uint8Array;
    cosmicHandle?: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum MessageType {
    file = "file",
    text = "text",
    image = "image"
}
export enum NFTCategory {
    guidedBreathwork = "guidedBreathwork",
    sageReflection = "sageReflection",
    deepShadow = "deepShadow",
    lightWisdom = "lightWisdom"
}
export enum OfferingType {
    art = "art",
    wisdom = "wisdom",
    breathwork = "breathwork",
    oneOnOne = "oneOnOne"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addGroupMember(groupId: string, memberVoidId: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    buyNFT(nftId: bigint, buyerVoidId: string): Promise<void>;
    createDM(voidId1: string, voidId2: string): Promise<string>;
    createGroup(name: string, creatorVoidId: string): Promise<string>;
    createValueOffering(title: string, description: string, priceVoid: bigint, offeringType: OfferingType, creatorVoidId: string): Promise<string>;
    deactivateOffering(offeringId: string, callerVoidId: string): Promise<void>;
    generateInviteToken(voidId: string): Promise<string>;
    getAllGroups(): Promise<Array<GroupInfo>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCosmicHandle(voidId: string): Promise<string | null>;
    getDailyReflection(): Promise<string | null>;
    getE2EEPublicKey(voidId: string): Promise<Uint8Array | null>;
    getGroupInfo(groupId: string): Promise<GroupInfo | null>;
    getGroupsForVoidId(voidId: string): Promise<Array<GroupInfo>>;
    getMarketplaceListings(category: NFTCategory | null): Promise<Array<CosmicNFT>>;
    getMessages(channel: string, count: bigint): Promise<Array<Message>>;
    getMessagesByKeyword(channel: string, keyword: string, count: bigint): Promise<Array<Message>>;
    getMintablePost(wisdomScore: bigint): Promise<boolean>;
    getNFT(nftId: bigint): Promise<CosmicNFT | null>;
    getNFTsByCreator(creatorVoidId: string): Promise<Array<CosmicNFT>>;
    getOfferingsByCreator(creatorVoidId: string): Promise<Array<ValueOffering>>;
    getPinnedMessage(channel: string): Promise<Message | null>;
    getRoyaltiesEarned(voidId: string): Promise<bigint>;
    getUserNFTs(voidId: string): Promise<Array<CosmicNFT>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getValueOfferings(): Promise<Array<ValueOffering>>;
    getWisdomScore(voidId: string): Promise<bigint>;
    isCallerAdmin(): Promise<boolean>;
    listChannels(): Promise<Array<ChannelType>>;
    listNFTForSale(nftId: bigint, priceVoid: bigint): Promise<void>;
    loadOlderMessages(channel: string, start: bigint, count: bigint): Promise<Array<Message>>;
    mintNFT(postText: string, wisdomScore: bigint, metadataJson: string, category: NFTCategory, creatorVoidId: string, rareTrait: string | null): Promise<bigint>;
    pinMessage(channel: string, messageId: string): Promise<void>;
    postMessage(channel: string, ciphertext: string, senderVoidId: string, messageType: MessageType, replyTo: string | null, blobId: string | null): Promise<void>;
    postMessageWithKeywords(channel: string, ciphertext: string, senderVoidId: string, messageType: MessageType, replyTo: string | null, blobId: string | null, keywords: Array<string>): Promise<void>;
    removeGroupMember(groupId: string, memberVoidId: string): Promise<void>;
    resolveInviteToken(token: string): Promise<string | null>;
    resonateNFT(nftId: bigint, resonatorVoidId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setCosmicHandle(voidId: string, handle: string): Promise<void>;
    setDailyReflection(text: string): Promise<void>;
    storeE2EEPublicKey(publicKey: Uint8Array): Promise<void>;
    upvoteMessage(channel: string, messageId: string): Promise<void>;
}
import type { ChannelType as _ChannelType, CosmicNFT as _CosmicNFT, GroupInfo as _GroupInfo, Message as _Message, MessageType as _MessageType, NFTCategory as _NFTCategory, OfferingType as _OfferingType, UserProfile as _UserProfile, UserRole as _UserRole, ValueOffering as _ValueOffering, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addGroupMember(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGroupMember(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGroupMember(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async buyNFT(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.buyNFT(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.buyNFT(arg0, arg1);
            return result;
        }
    }
    async createDM(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createDM(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDM(arg0, arg1);
            return result;
        }
    }
    async createGroup(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createGroup(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGroup(arg0, arg1);
            return result;
        }
    }
    async createValueOffering(arg0: string, arg1: string, arg2: bigint, arg3: OfferingType, arg4: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createValueOffering(arg0, arg1, arg2, to_candid_OfferingType_n10(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createValueOffering(arg0, arg1, arg2, to_candid_OfferingType_n10(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async deactivateOffering(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateOffering(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateOffering(arg0, arg1);
            return result;
        }
    }
    async generateInviteToken(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateInviteToken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateInviteToken(arg0);
            return result;
        }
    }
    async getAllGroups(): Promise<Array<GroupInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGroups();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGroups();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCosmicHandle(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCosmicHandle(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCosmicHandle(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyReflection(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyReflection();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyReflection();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getE2EEPublicKey(arg0: string): Promise<Uint8Array | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getE2EEPublicKey(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getE2EEPublicKey(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGroupInfo(arg0: string): Promise<GroupInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroupInfo(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroupInfo(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGroupsForVoidId(arg0: string): Promise<Array<GroupInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroupsForVoidId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroupsForVoidId(arg0);
            return result;
        }
    }
    async getMarketplaceListings(arg0: NFTCategory | null): Promise<Array<CosmicNFT>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketplaceListings(to_candid_opt_n20(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketplaceListings(to_candid_opt_n20(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(arg0: string, arg1: bigint): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0, arg1);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0, arg1);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessagesByKeyword(arg0: string, arg1: string, arg2: bigint): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessagesByKeyword(arg0, arg1, arg2);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessagesByKeyword(arg0, arg1, arg2);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMintablePost(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getMintablePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMintablePost(arg0);
            return result;
        }
    }
    async getNFT(arg0: bigint): Promise<CosmicNFT | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNFT(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNFT(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNFTsByCreator(arg0: string): Promise<Array<CosmicNFT>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNFTsByCreator(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNFTsByCreator(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOfferingsByCreator(arg0: string): Promise<Array<ValueOffering>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOfferingsByCreator(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOfferingsByCreator(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPinnedMessage(arg0: string): Promise<Message | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPinnedMessage(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPinnedMessage(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoyaltiesEarned(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoyaltiesEarned(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoyaltiesEarned(arg0);
            return result;
        }
    }
    async getUserNFTs(arg0: string): Promise<Array<CosmicNFT>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserNFTs(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserNFTs(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getValueOfferings(): Promise<Array<ValueOffering>> {
        if (this.processError) {
            try {
                const result = await this.actor.getValueOfferings();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getValueOfferings();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWisdomScore(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getWisdomScore(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWisdomScore(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listChannels(): Promise<Array<ChannelType>> {
        if (this.processError) {
            try {
                const result = await this.actor.listChannels();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listChannels();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async listNFTForSale(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.listNFTForSale(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listNFTForSale(arg0, arg1);
            return result;
        }
    }
    async loadOlderMessages(arg0: string, arg1: bigint, arg2: bigint): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.loadOlderMessages(arg0, arg1, arg2);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loadOlderMessages(arg0, arg1, arg2);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async mintNFT(arg0: string, arg1: bigint, arg2: string, arg3: NFTCategory, arg4: string, arg5: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.mintNFT(arg0, arg1, arg2, to_candid_NFTCategory_n21(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n43(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.mintNFT(arg0, arg1, arg2, to_candid_NFTCategory_n21(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n43(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async pinMessage(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.pinMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pinMessage(arg0, arg1);
            return result;
        }
    }
    async postMessage(arg0: string, arg1: string, arg2: string, arg3: MessageType, arg4: string | null, arg5: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.postMessage(arg0, arg1, arg2, to_candid_MessageType_n44(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n43(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n43(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postMessage(arg0, arg1, arg2, to_candid_MessageType_n44(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n43(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n43(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async postMessageWithKeywords(arg0: string, arg1: string, arg2: string, arg3: MessageType, arg4: string | null, arg5: string | null, arg6: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.postMessageWithKeywords(arg0, arg1, arg2, to_candid_MessageType_n44(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n43(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n43(this._uploadFile, this._downloadFile, arg5), arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postMessageWithKeywords(arg0, arg1, arg2, to_candid_MessageType_n44(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n43(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n43(this._uploadFile, this._downloadFile, arg5), arg6);
            return result;
        }
    }
    async removeGroupMember(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeGroupMember(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeGroupMember(arg0, arg1);
            return result;
        }
    }
    async resolveInviteToken(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.resolveInviteToken(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resolveInviteToken(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async resonateNFT(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resonateNFT(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resonateNFT(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n46(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n46(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setCosmicHandle(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCosmicHandle(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCosmicHandle(arg0, arg1);
            return result;
        }
    }
    async setDailyReflection(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDailyReflection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDailyReflection(arg0);
            return result;
        }
    }
    async storeE2EEPublicKey(arg0: Uint8Array): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storeE2EEPublicKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeE2EEPublicKey(arg0);
            return result;
        }
    }
    async upvoteMessage(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upvoteMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upvoteMessage(arg0, arg1);
            return result;
        }
    }
}
function from_candid_ChannelType_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChannelType): ChannelType {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_CosmicNFT_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CosmicNFT): CosmicNFT {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_MessageType_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageType): MessageType {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Message_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Message {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_NFTCategory_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NFTCategory): NFTCategory {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_OfferingType_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OfferingType): OfferingType {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_ValueOffering_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ValueOffering): ValueOffering {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GroupInfo]): GroupInfo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CosmicNFT]): CosmicNFT | null {
    return value.length === 0 ? null : from_candid_CosmicNFT_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Message]): Message | null {
    return value.length === 0 ? null : from_candid_Message_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    voidId: string;
    e2eePublicKey: [] | [Uint8Array];
    cosmicHandle: [] | [string];
}): {
    voidId: string;
    e2eePublicKey?: Uint8Array;
    cosmicHandle?: string;
} {
    return {
        voidId: value.voidId,
        e2eePublicKey: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.e2eePublicKey)),
        cosmicHandle: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.cosmicHandle))
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    postText: string;
    creator: Principal;
    resonanceCount: bigint;
    lineage: Array<string>;
    rareTrait: [] | [string];
    metadataJson: string;
    creatorVoidId: string;
    mintedAt: bigint;
    wisdomScore: bigint;
    category: _NFTCategory;
    priceVoid: bigint;
    isForSale: boolean;
}): {
    id: bigint;
    postText: string;
    creator: Principal;
    resonanceCount: bigint;
    lineage: Array<string>;
    rareTrait?: string;
    metadataJson: string;
    creatorVoidId: string;
    mintedAt: bigint;
    wisdomScore: bigint;
    category: NFTCategory;
    priceVoid: bigint;
    isForSale: boolean;
} {
    return {
        id: value.id,
        postText: value.postText,
        creator: value.creator,
        resonanceCount: value.resonanceCount,
        lineage: value.lineage,
        rareTrait: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.rareTrait)),
        metadataJson: value.metadataJson,
        creatorVoidId: value.creatorVoidId,
        mintedAt: value.mintedAt,
        wisdomScore: value.wisdomScore,
        category: from_candid_NFTCategory_n26(_uploadFile, _downloadFile, value.category),
        priceVoid: value.priceVoid,
        isForSale: value.isForSale
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    upvotes: bigint;
    senderVoidId: string;
    ciphertext: string;
    keywords: Array<string>;
    messageType: _MessageType;
    timestamp: bigint;
    blobId: [] | [string];
    replyTo: [] | [string];
}): {
    id: string;
    upvotes: bigint;
    senderVoidId: string;
    ciphertext: string;
    keywords: Array<string>;
    messageType: MessageType;
    timestamp: bigint;
    blobId?: string;
    replyTo?: string;
} {
    return {
        id: value.id,
        upvotes: value.upvotes,
        senderVoidId: value.senderVoidId,
        ciphertext: value.ciphertext,
        keywords: value.keywords,
        messageType: from_candid_MessageType_n31(_uploadFile, _downloadFile, value.messageType),
        timestamp: value.timestamp,
        blobId: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.blobId)),
        replyTo: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.replyTo))
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    createdAt: bigint;
    description: string;
    creatorVoidId: string;
    isActive: boolean;
    offeringType: _OfferingType;
    priceVoid: bigint;
}): {
    id: string;
    title: string;
    createdAt: bigint;
    description: string;
    creatorVoidId: string;
    isActive: boolean;
    offeringType: OfferingType;
    priceVoid: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        createdAt: value.createdAt,
        description: value.description,
        creatorVoidId: value.creatorVoidId,
        isActive: value.isActive,
        offeringType: from_candid_OfferingType_n37(_uploadFile, _downloadFile, value.offeringType),
        priceVoid: value.priceVoid
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    guidedBreathwork: null;
} | {
    sageReflection: null;
} | {
    deepShadow: null;
} | {
    lightWisdom: null;
}): NFTCategory {
    return "guidedBreathwork" in value ? NFTCategory.guidedBreathwork : "sageReflection" in value ? NFTCategory.sageReflection : "deepShadow" in value ? NFTCategory.deepShadow : "lightWisdom" in value ? NFTCategory.lightWisdom : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    file: null;
} | {
    text: null;
} | {
    image: null;
}): MessageType {
    return "file" in value ? MessageType.file : "text" in value ? MessageType.text : "image" in value ? MessageType.image : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    art: null;
} | {
    wisdom: null;
} | {
    breathwork: null;
} | {
    oneOnOne: null;
}): OfferingType {
    return "art" in value ? OfferingType.art : "wisdom" in value ? OfferingType.wisdom : "breathwork" in value ? OfferingType.breathwork : "oneOnOne" in value ? OfferingType.oneOnOne : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dm: string;
} | {
    darkRoom: null;
} | {
    group: string;
} | {
    lightRoom: null;
}): {
    __kind__: "dm";
    dm: string;
} | {
    __kind__: "darkRoom";
    darkRoom: null;
} | {
    __kind__: "group";
    group: string;
} | {
    __kind__: "lightRoom";
    lightRoom: null;
} {
    return "dm" in value ? {
        __kind__: "dm",
        dm: value.dm
    } : "darkRoom" in value ? {
        __kind__: "darkRoom",
        darkRoom: value.darkRoom
    } : "group" in value ? {
        __kind__: "group",
        group: value.group
    } : "lightRoom" in value ? {
        __kind__: "lightRoom",
        lightRoom: value.lightRoom
    } : value;
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CosmicNFT>): Array<CosmicNFT> {
    return value.map((x)=>from_candid_CosmicNFT_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Array<Message> {
    return value.map((x)=>from_candid_Message_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ValueOffering>): Array<ValueOffering> {
    return value.map((x)=>from_candid_ValueOffering_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChannelType>): Array<ChannelType> {
    return value.map((x)=>from_candid_ChannelType_n41(_uploadFile, _downloadFile, x));
}
function to_candid_MessageType_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageType): _MessageType {
    return to_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function to_candid_NFTCategory_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NFTCategory): _NFTCategory {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_OfferingType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OfferingType): _OfferingType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n47(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NFTCategory | null): [] | [_NFTCategory] {
    return value === null ? candid_none() : candid_some(to_candid_NFTCategory_n21(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    voidId: string;
    e2eePublicKey?: Uint8Array;
    cosmicHandle?: string;
}): {
    voidId: string;
    e2eePublicKey: [] | [Uint8Array];
    cosmicHandle: [] | [string];
} {
    return {
        voidId: value.voidId,
        e2eePublicKey: value.e2eePublicKey ? candid_some(value.e2eePublicKey) : candid_none(),
        cosmicHandle: value.cosmicHandle ? candid_some(value.cosmicHandle) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OfferingType): {
    art: null;
} | {
    wisdom: null;
} | {
    breathwork: null;
} | {
    oneOnOne: null;
} {
    return value == OfferingType.art ? {
        art: null
    } : value == OfferingType.wisdom ? {
        wisdom: null
    } : value == OfferingType.breathwork ? {
        breathwork: null
    } : value == OfferingType.oneOnOne ? {
        oneOnOne: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NFTCategory): {
    guidedBreathwork: null;
} | {
    sageReflection: null;
} | {
    deepShadow: null;
} | {
    lightWisdom: null;
} {
    return value == NFTCategory.guidedBreathwork ? {
        guidedBreathwork: null
    } : value == NFTCategory.sageReflection ? {
        sageReflection: null
    } : value == NFTCategory.deepShadow ? {
        deepShadow: null
    } : value == NFTCategory.lightWisdom ? {
        lightWisdom: null
    } : value;
}
function to_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageType): {
    file: null;
} | {
    text: null;
} | {
    image: null;
} {
    return value == MessageType.file ? {
        file: null
    } : value == MessageType.text ? {
        text: null
    } : value == MessageType.image ? {
        image: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
